### ISSUE TITLE
Map moves on scroll in details window

### ISSUE THREAD

**Issue by gerbsen** [route360/laupi#2]
in der Demo bewegt sich die karte beim Scrollen im Detailfenster links.
In Firefox.

**Comment by hollburg** [comment]
Ähnliches Problem im InternetExplorer. Wenn man auf den Scrollbar klickt verfängt sich das in der Karte

**Comment by j-slvr** [comment]
in ff ist der fehler bei mir reproduzierbar. im ie ist alles ok

**Comment by hollburg** [comment]
chrome geht bei mir auch. Bei IE tritt der Fehler auch erst nach dem scrollen auf

**Comment by j-slvr** [comment]
habe die detail-view aus dem map-div herausgeholt. jetzt gehts.
